window.ARTICLE_GRAFS = {
  cover: {
    en: [
      "The sitting was not a sitting. It was an arrangement of light, cloth, and the decision not to explain. What could not survive reprint was taken out before the plate was made.",
      "A cover of this kind does not argue. It occupies. The room learns the name by looking, then looking away, then looking again.",
      "Colour was treated as rank, and cloth as biography. Jewellery, location, even a second line of type were declined. The object was asked to hold still until the issue could travel without a slogan.",
      "Printers speak of plates as if they were manners. This one was finished early, then left alone. The desk prefers a cover that can be recognised from across a table and still not be summarised.",
      "By the time the issue left the press, the headline had already become unnecessary. The object had done the work.",
    ],
    ar: [
      "لم يكن الجلوس جلوسًا. كان ترتيب ضوء وقماش وقرارًا بألا يُشرح شيء. ما لا يصمد أمام إعادة الطبع أُخرج قبل صنع اللوح.",
      "غلاف من هذا النوع لا يجادل. يحتل. تتعلم الغرفة الاسم بالنظر، ثم بالإعراض، ثم بالنظر مرة أخرى.",
      "عُومل اللون كرتبة والقماش كسيرة. رُفضت الحلي والمكان حتى سطر ثانٍ من الحرف. طُلب من الشيء أن يثبت حتى تسافر الطبعة بلا شعار.",
      "يتكلم عمال المطبعة عن الألواح كأنّها آداب. أُنجز هذا مبكرًا ثم تُرك. يفضّل المكتب غلافًا يُعرف من عبر المائدة ولا يُختصر.",
      "حين غادرت الطبعة المطبعة كان العنوان قد صار زائدًا. قام الشيء بالعمل.",
    ],
    ru: [
      "Съёмка не была съёмкой. Это была постановка света, ткани и решения ничего не объяснять. Что не выдержало бы перепечатки, убрали до пластины.",
      "Такая обложка не спорит. Она занимает место. Зал учит имя, глядя, отводя взгляд и глядя снова.",
      "Цвет держали как ранг, ткань — как биографию. Украшения, место, даже вторую строку набора отклонили. Предмет должен был выдержать, пока номер не уйдёт без слогана.",
      "Печатники говорят о пластинах, как о манерах. Эту закончили рано и оставили. Редакция любит обложку, которую узнают через стол и всё равно не перескажут.",
      "К тому моменту, как номер вышел из печати, заголовок уже был лишним. Работу сделал предмет.",
    ],
  },
  profile: {
    en: [
      "The portrait is a study in delay. He does not fill the frame; he lets the furniture, the window, and the pause do it for him.",
      "Those who expected charm were given proportion. It lasts longer, and it photographs better in winter light.",
      "Upholstery was chosen before the suit. The chair at the end of the table is not the loudest seat. It is the one from which the evening is decided.",
      "He arrives last on purpose. The room rearranges around that fact, which is a kind of courtesy and a kind of rank. No one is asked to name it.",
      "When the sitting ended, nothing had been confessed. That, the desk noted, was the most expensive thing in the room.",
    ],
    ar: [
      "البورتريه دراسة في التأخير. لا يملأ الإطار؛ يدع الأثاث والنافذة والوقفة تفعل ذلك.",
      "من انتظر فتنة أُعطي تناسبًا. هو أطول عمرًا، ويُصوَّر أجمل في ضوء الشتاء.",
      "اختير التنجيد قبل البدلة. الكرسي في نهاية المائدة ليس الأعلى صوتًا. هو المقعد الذي يُحسم منه المساء.",
      "يصل أخيرًا عمدًا. تعيد الغرفة ترتيب نفسها حول تلك الحقيقة، وهو لطف وهو رتبة. لا يُطلب من أحد أن يسمّيه.",
      "حين انتهى الجلوس لم يُعترف بشيء. وذاك، كما دوّن المكتب، أغلى ما في الغرفة.",
    ],
    ru: [
      "Портрет — этюд о задержке. Он не заполняет кадр: за него это делают мебель, окно и пауза.",
      "Тем, кто ждал обаяния, дали пропорцию. Она живёт дольше и лучше ложится на зимний свет.",
      "Обивку выбрали раньше костюма. Кресло в конце стола — не самое громкое. С него решают вечер.",
      "Он входит последним нарочно. Зал перестраивается вокруг этого факта — это и любезность, и ранг. Называть это никого не просят.",
      "Когда съёмка кончилась, ничего не было сказано. Это, отметила редакция, оказалось самым дорогим в комнате.",
    ],
  },
  interview: {
    en: [
      "The useful answers lived in the pause. Questions that asked for a slogan were returned, politely, unanswered.",
      "She treated the recorder as a guest with a coat still on: welcome, not intimate. Every sentence was cut before it left the table.",
      "The hour was long. The usable hour was not. What could not be said in public was not hinted at either; it was left off the page, which is a form of editing and a form of protection.",
      "Reprint is a kind of weather. A sentence that cannot survive it is not a sentence the desk will keep. She knew this before the first question was asked.",
      "The transcript, when it arrived, was shorter than the hour. That is how the desk knows the hour was well spent.",
    ],
    ar: [
      "الإجابات النافعة سكنت في الوقفة. الأسئلة التي طلبت شعارًا أُعيدت بأدب بلا جواب.",
      "عاملت المسجّل كضيف ما زال بمعطفه: مرحبًا به، غير حميم. كل جملة قُصّت قبل أن تغادر المائدة.",
      "كانت الساعة طويلة. أما الساعة النافعة فلم تكن. ما لا يُقال أمام الجمهور لم يُلمَّح إليه؛ تُرك خارج الصفحة، وهو تحرير وهو حماية.",
      "إعادة الطبع ضرب من الطقس. الجملة التي لا تصمد ليست جملة يبقيها المكتب. عرفت ذلك قبل السؤال الأول.",
      "جاء النص أقصر من الساعة. هكذا يعرف المكتب أن الساعة أُنفقت حسنًا.",
    ],
    ru: [
      "Нужные ответы жили в паузе. Вопросы, которые просили слоган, вежливо вернули без ответа.",
      "Она держала диктофон как гостя в пальто: принято, но не близко. Каждая фраза обрезана до того, как покинула стол.",
      "Час был длинным. Нужный час — нет. Что нельзя сказать при всех, не намекали: оставили за страницей. Это и правка, и защита.",
      "Перепечатка — своего рода погода. Фразу, которая её не выдержит, редакция не хранит. Она знала это до первого вопроса.",
      "Расшифровка пришла короче часа. Так редакция понимает, что час был потрачен верно.",
    ],
  },
  society: {
    en: [
      "No card at the door, no toast that needed a microphone. Those who had to know had already taken their seats.",
      "Absence, correctly staged, is a guest. The table understood. So did everyone who was not asked to sit.",
      "The gown held the light and the list became a rumour by midnight. That is how a season opens when it still believes in rooms rather than feeds.",
      "Three empty seats were left on purpose. They did more work than a seating plan. The evening was complete before anyone sat down, which is rarer than it sounds.",
      "When the lights cooled, the evening became private again. That is the hour the house is retained to protect.",
    ],
    ar: [
      "لا بطاقة عند الباب، ولا نخب يحتاج ميكروفونًا. من كان عليه أن يعرف كان قد جلس.",
      "الغياب، إذا أُخرج بإتقان، ضيف. فهمت المائدة. وفهم من لم يُدعَ للجلوس.",
      "أمسك الفستان بالضوء وصارت القائمة إشاعة عند منتصف الليل. هكذا يُفتتح موسم ما زال يؤمن بالغرف لا بالتغذيات.",
      "تُركت ثلاثة مقاعد فارغة عمدًا. عملت أكثر من خطة جلوس. اكتملت الأمسية قبل أن يجلس أحد، وهو أندر مما يبدو.",
      "حين بردت الأضواء عاد المساء خاصًا. تلك الساعة تُعهَد الدار بحمايتها.",
    ],
    ru: [
      "Ни карточки у двери, ни тоста под микрофон. Те, кому следовало знать, уже сидели.",
      "Верно поставленное отсутствие — тоже гость. Стол понял. И те, кого не посадили, — тоже.",
      "Платье держало свет, а список к полуночи стал слухом. Так открывается сезон, который ещё верит в комнаты, а не в ленты.",
      "Три места оставили пустыми нарочно. Они сделали больше, чем план рассадки. Вечер был готов до того, как кто-то сел — это реже, чем кажется.",
      "Когда огни остыли, вечер снова стал частным. Этот час дом нанимают беречь.",
    ],
  },
  dispatch: {
    en: [
      "The copy was filed before the city admitted it was morning. Whoever placed the story had already left the building.",
      "Numbers would follow. The sentence had already chosen its tense. That is the difference between a leak and a briefing.",
      "Paper, coffee, dawn. A morning note that arrives before the bell is not haste. It is sequence. The markets would open to a story that had already taken its shape.",
      "Reprint will try to soften it. The desk wrote it so that softening would look like a mistake. Tense is a kind of architecture.",
      "By the time the first coffee was poured, the story had taken its final shape — and could not be unwritten.",
    ],
    ar: [
      "أُرسل النص قبل أن تعترف المدينة بالصباح. من وضع الخبر كان قد غادر المبنى.",
      "الأرقام ستأتي. الجملة اختارت زمنها. ذاك الفرق بين تسرّب وإحاطة.",
      "ورق وقهوة وفجر. ملاحظة صباحية تصل قبل الجرس ليست عجلة. هي تسلسل. ستُفتح الأسواق على قصة اتخذت شكلها.",
      "ستحاول إعادة الطبع تليينها. كتبها المكتب بحيث يبدو التليين خطأ. الزمن النحوي عمارة.",
      "حين صُبّت أول قهوة كانت القصة قد اتخذت شكلها الأخير — ولم يعد ممكنًا محوها.",
    ],
    ru: [
      "Текст сдали раньше, чем город признал утро. Тот, кто поставил материал, уже вышел из здания.",
      "Цифры подтянутся. Предложение уже выбрало время. В этом разница между утечкой и брифингом.",
      "Бумага, кофе, рассвет. Записка до колокола — не спешка, а последовательность. Рынки откроются к истории, которая уже приняла форму.",
      "Перепечатка попытается смягчить. Редакция написала так, чтобы смягчение выглядело ошибкой. Время глагола — тоже архитектура.",
      "К первому кофе история приняла окончательную форму — и её уже нельзя было отменить.",
    ],
  },
  event: {
    en: [
      "The collection, the speech, the dance — each was shown once. The room understood it twice: in the language of the guests, then in the language the hosts actually speak.",
      "Applause would have been too cheap a close. The room adjusted instead, which is rarer, and more useful.",
      "Velvet, a gold rope, no logo. A curtain photographed as if it were a face. Luxury, at its highest, is withholding, and withholding is a timetable.",
      "Front row is a second language. Sequence does the rest: who enters, who is lit, who is left unnamed until the cameras have gone and the evening can become private again.",
      "Cameras left on time. The last hour belonged to those who had never needed to be announced.",
    ],
    ar: [
      "المجموعة، الخطاب، الرقصة — عُرض كل منها مرة. وفهمتها الغرفة مرتين: بلغة الضيوف، ثم باللغة التي يتكلمها المضيفون فعلًا.",
      "التصفيق كان ليكون ختامًا رخيصًا. عدّلت الغرفة وضعها بدلًا منه، وهذا أندر وأنفع.",
      "مخمل وحبل ذهب ولا شعار. ستار صُوِّر كأنه وجه. الفخامة في ذروتها إمساك، والإمساك جدول.",
      "الصف الأول لغة ثانية. يقوم التسلسل بالباقي: من يدخل، من يُضاء، من يُترك بلا اسم حتى تغادر الكاميرات ويعود المساء خاصًا.",
      "غادرت الكاميرات في وقتها. الساعة الأخيرة كانت لمن لم يحتج إلى إعلان.",
    ],
    ru: [
      "Коллекцию, речь, танец показали по разу. Зал понял дважды: на языке гостей и на языке, на котором говорят хозяева.",
      "Аплодисменты были бы слишком дешёвым финалом. Зал перестроился — это реже и нужнее.",
      "Бархат, золотой шнур, без логотипа. Занавес, снятый как лицо. Высшая роскошь — в умении не показывать, а не показывать — это расписание.",
      "Первый ряд — второй язык. Остальное делает последовательность: кто входит, кого освещают, кого не называют, пока камеры не уйдут и вечер снова станет частным.",
      "Камеры ушли вовремя. Последний час принадлежал тем, кого никогда не объявляли.",
    ],
  },
  city: {
    en: [
      "After midnight the towers keep their own counsel. The story is never the skyline. It is who is still awake inside it.",
      "Capital, in this telling, is a light left on in a private floor — not a performance for the river.",
      "A city that prefers to whisper will still print. The dawn papers arrived warm because someone had to file before the first coffee, and someone else had to decide which windows counted as news.",
      "Skyline is a publicist’s word. The desk prefers floors, hours, and the particular silence of a street that knows it is being watched and declines to perform.",
      "Dawn papers arrived still warm. The city, as ever, preferred to whisper.",
    ],
    ar: [
      "بعد منتصف الليل تحتفظ الأبراج برأيها. القصة ليست الأفق أبدًا. بل من لا يزال مستيقظًا داخله.",
      "رأس المال، في هذا السرد، ضوء متروك في طابق خاص — لا عرضًا للنهر.",
      "مدينة تفضّل الهمس ما زالت تطبع. وصلت صحف الفجر دافئة لأن أحدًا كان عليه أن يرسل قبل أول قهوة، وآخر أن يقرر أي النوافذ تُعدّ خبرًا.",
      "الأفق كلمة مستشار إعلامي. يفضّل المكتب الطوابق والساعات وصمت شارع يعرف أنه يُراقَب ويرفض أن يؤدّي.",
      "وصلت صحف الفجر دافئة. والمدينة، كما دائمًا، فضّلت الهمس.",
    ],
    ru: [
      "После полуночи башни держат совет сами. История никогда не в силуэте. А в том, кто ещё не спит внутри.",
      "Капитал в этом рассказе — свет на частном этаже, а не спектакль для реки.",
      "Город, который предпочитает шёпот, всё равно печатает. Утренние газеты пришли тёплыми, потому что кто-то сдал текст до первого кофе, а кто-то решил, какие окна считаются новостью.",
      "Силуэт — слово пиарщика. Редакция предпочитает этажи, часы и тишину улицы, которая знает, что на неё смотрят, и отказывается выступать.",
      "Утренние газеты пришли ещё тёплыми. Город, как всегда, предпочёл шёпот.",
    ],
  },
  letter: {
    en: [
      "Ink, blotter, and a sentence that will outlive the week. Correspondence remains the luxury that cannot be edited in public.",
      "Handwritten notes still move ministries. The photograph is of the instrument; the news is of the recipient.",
      "A pen, a terrace, a country. The letter was never meant for the archive. It was meant to arrive, to be read once, and to leave a silence that a press release cannot imitate.",
      "East light is useful for this kind of work. It does not flatter. It records. The desk has always trusted paper more than a feed, and a signature more than a slogan.",
      "The letter was never meant for the archive. It was meant to arrive — and to be read once.",
    ],
    ar: [
      "حبر ونشاف وجملة تعيش أطول من الأسبوع. المراسلة ما زالت الترف الذي لا يُحرَّر أمام الجمهور.",
      "الملاحظات بخط اليد ما زالت تحرّك الوزارات. الصورة للأداة؛ والخبر لمن استلمها.",
      "قلم وشرفة وبلد. الرسالة لم تُكتب للأرشيف. كُتبت لتصل وتُقرأ مرة وتترك صمتًا لا يقدر بيان على تقليده.",
      "ضوء الشرق نافع لهذا العمل. لا يجامل. يسجّل. ما زال المكتب يثق بالورق أكثر من التغذية، وبالتوقيع أكثر من الشعار.",
      "الرسالة لم تُكتب للأرشيف. كُتبت لتصل — ولتُقرأ مرة.",
    ],
    ru: [
      "Чернила, промокашка и фраза, которая переживёт неделю. Переписка — роскошь, которую не правят при всех.",
      "Рукописные записки всё ещё двигают министерства. На снимке инструмент; новость — в адресате.",
      "Перо, терраса, страна. Письмо не предназначалось архиву. Оно должно было дойти, быть прочитано один раз и оставить тишину, которую пресс-релиз не сымитирует.",
      "Восточный свет годится для такой работы. Он не льстит. Он фиксирует. Редакция всегда доверяла бумаге больше ленты, а подписи — больше слогана.",
      "Письмо не предназначалось архиву. Оно должно было дойти — и быть прочитано один раз.",
    ],
  },
  launch: {
    en: [
      "Nothing was “unveiled”. The object was simply allowed into the room, and the room was already dressed for it.",
      "A launch of this house is a question of sequence: who sees, who is lit, who is left unnamed until the second edition.",
      "The long corridor does not display power. It delays it, beautifully, until the door. Brass and marble are not decoration; they are a timetable in stone.",
      "By the time the carpet has swallowed the last footstep, the name has already travelled. No slogan is required. The room has done the announcing.",
      "By evening the name had travelled without a slogan. That is how the desk measures a beginning.",
    ],
    ar: [
      "لم يُكشف عن شيء. سُمح للشيء بدخول الغرفة، وكانت الغرفة قد لبست لأجله.",
      "إطلاق هذه الدار مسألة تسلسل: من يرى، من يُضاء، من يُترك بلا اسم حتى الطبعة الثانية.",
      "الممر الطويل لا يعرض القوة. يؤجّلها بجمال حتى الباب. النحاس والرخام ليسا زينة؛ هما جدول في حجر.",
      "حين يبتلع البساط آخر خطوة يكون الاسم قد سافر. لا حاجة إلى شعار. قامت الغرفة بالإعلان.",
      "مع المساء سافر الاسم بلا شعار. هكذا يقيس المكتب البداية.",
    ],
    ru: [
      "Ничего не «презентировали». Предмет просто впустили в зал, и зал уже был к нему готов.",
      "Запуск этого дома — вопрос последовательности: кто видит, кого освещают, кого не называют до второго выпуска.",
      "Длинный коридор не выставляет власть. Он красиво откладывает её до двери. Латунь и мрамор — не декор, а расписание в камне.",
      "Когда ковёр проглотил последний шаг, имя уже ушло. Слоган не нужен. Зал объявил сам.",
      "К вечеру имя ушло без слогана. Так редакция измеряет начало.",
    ],
  },
  campaign: {
    en: [
      "The campaign was not a burst. It was a season: the same sentence, held, until the market could say it without being told.",
      "Media plans that announce themselves are already late. This one arrived as if it had always been in the paper.",
      "A supper that never needed a list is still a kind of media. Empty seats, correctly left, do more than a seating chart. The evening was complete before anyone sat down.",
      "Nothing felt finished when it closed — only correctly placed. The desk prefers that kind of ending, because it can be continued without being repeated.",
      "When it closed, nothing felt finished — only correctly placed. The desk prefers that kind of ending.",
    ],
    ar: [
      "لم تكن الحملة دفعة. كانت موسمًا: الجملة نفسها، ممسوكة، حتى يقولها السوق من دون أن يُلقَّن.",
      "خطط الإعلام التي تعلن عن نفسها متأخرة سلفًا. هذه وصلت كأنها كانت في الصحيفة دائمًا.",
      "عشاء لا يحتاج قائمة ما زال ضربًا من الإعلام. المقاعد الفارغة، إذا تُركت بإتقان، تفعل أكثر من خطة جلوس. اكتملت الأمسية قبل أن يجلس أحد.",
      "حين أُغلقت لم يبدُ شيء مكتملًا — بل موضوعًا في موضعه. يفضّل المكتب ذلك الختام لأنه يُستأنف من دون أن يُعاد.",
      "حين أُغلقت لم يبدُ شيء مكتملًا — بل موضوعًا في موضعه. يفضّل المكتب ذلك الختام.",
    ],
    ru: [
      "Кампания не была вспышкой. Это был сезон: одна и та же фраза, пока рынок не стал говорить её сам.",
      "Медиапланы, которые сами себя объявляют, уже опоздали. Этот пришёл так, будто всегда был в газете.",
      "Ужин без списка — тоже медиа. Пустые места, верно оставленные, делают больше схемы рассадки. Вечер был готов до того, как кто-то сел.",
      "Когда её закрыли, ничего не казалось завершённым — только верно поставленным. Такой финал редакция любит: его можно продолжить, не повторяя.",
      "Когда её закрыли, ничего не казалось завершённым — только верно поставленным. Такой финал редакция любит.",
    ],
  },
};
