window.NEWS_TYPES = [
  "cover",
  "profile",
  "interview",
  "society",
  "dispatch",
  "event",
  "city",
  "letter",
  "launch",
  "campaign",
];

window.NEWS = [
  {
    img: "01",
    outlet: "Forbes",
    date: "2026-03-14",
    kind: "cover",
    title: {
      en: "The quiet architecture of a name",
      ar: "الهندسة الهادئة للاسم",
      ru: "Тихая архитектура имени",
    },
    lede: {
      en: "A cover built from cloth, type, and patience. The house does not shout; it is simply the object the room is arranged around.",
      ar: "غلاف صُنع من قماش وحرف وصبر. الدار لا ترفع صوتها؛ هي الشيء الذي تُرتَّب الغرفة من حوله.",
      ru: "Обложка из ткани, шрифта и терпения. Дом не повышает голос — вокруг него просто выстраивается зал.",
    },
  },
  {
    img: "02",
    outlet: "Tatler",
    date: "2026-02-08",
    kind: "society",
    title: {
      en: "Midnight in the winter salon",
      ar: "منتصف الليل في صالون الشتاء",
      ru: "Полночь в зимнем салоне",
    },
    lede: {
      en: "The season opened not with a speech, but with a gown that held the light. By twelve, the list had become a rumour.",
      ar: "لم يُفتتح الموسم بخطاب، بل بفستان أمسك بالضوء. وعند منتصف الليل صارت القائمة إشاعة.",
      ru: "Сезон открылся не речью, а платьем, которое держало свет. К полуночи список стал слухом.",
    },
  },
  {
    img: "03",
    outlet: "Esquire",
    date: "2026-01-22",
    kind: "profile",
    title: {
      en: "He arrives last, and the room rearranges",
      ar: "يصل أخيرًا، فتعيد الغرفة ترتيب نفسها",
      ru: "Он входит последним — и зал перестраивается",
    },
    lede: {
      en: "A portrait of a principal who treats presence as a craft. The chair is never accidental. Neither is the silence that follows.",
      ar: "بورتريه لرئيس يعامل الحضور كحرفة. الكرسي ليس مصادفة. ولا الصمت الذي يليه.",
      ru: "Портрет принципала, для которого присутствие — ремесло. Кресло не случайно. И тишина после него — тоже.",
    },
  },
  {
    img: "04",
    outlet: "Marie Claire",
    date: "2025-12-11",
    kind: "interview",
    title: {
      en: "On the discipline of being seen",
      ar: "في انضباط أن تُرى",
      ru: "О дисциплине быть на виду",
    },
    lede: {
      en: "She speaks as if the microphone were a guest. Every sentence is cut before it leaves the table. The rest is withheld, on purpose.",
      ar: "تتكلم كأن الميكروفون ضيف. كل جملة تُقصّ قبل أن تغادر المائدة. والباقي يُحبَس عمدًا.",
      ru: "Она говорит так, будто микрофон — гость. Каждая фраза обрезана до того, как покинет стол. Остальное удержано нарочно.",
    },
  },
  {
    img: "05",
    outlet: "Associated Press",
    date: "2025-11-03",
    kind: "city",
    title: {
      en: "A city that prefers to whisper",
      ar: "مدينة تفضّل الهمس",
      ru: "Город, который предпочитает шёпот",
    },
    lede: {
      en: "After midnight the towers keep their own counsel. The story, as ever, is not the skyline — it is who is still awake inside it.",
      ar: "بعد منتصف الليل تحتفظ الأبراج برأيها. القصة، كما دائمًا، ليست الأفق — بل من لا يزال مستيقظًا داخله.",
      ru: "После полуночи башни держат совет сами с собой. История, как всегда, не в силуэте — а в том, кто ещё не спит внутри.",
    },
  },
  {
    img: "06",
    outlet: "Forbes",
    date: "2025-10-19",
    kind: "letter",
    title: {
      en: "Letters from the east terrace",
      ar: "رسائل من الشرفة الشرقية",
      ru: "Письма с восточной террасы",
    },
    lede: {
      en: "Ink, blotter, and a sentence that will outlive the week. Correspondence remains the most expensive luxury: a thought that cannot be edited in public.",
      ar: "حبر ونشاف وجملة تعيش أطول من الأسبوع. المراسلة ما زالت أغلى ترف: فكرة لا تُحرَّر أمام الجمهور.",
      ru: "Чернила, промокашка и фраза, которая переживёт неделю. Переписка — всё ещё самая дорогая роскошь: мысль, которую не правят при всех.",
    },
  },
  {
    img: "07",
    outlet: "Tatler",
    date: "2025-09-27",
    kind: "launch",
    title: {
      en: "The long corridor, and what it admits",
      ar: "الممر الطويل، وما يسمح بدخوله",
      ru: "Длинный коридор и то, что он впускает",
    },
    lede: {
      en: "Brass, marble, and a carpet that swallows footsteps. Houses of this kind do not display power. They delay it, beautifully, until the door.",
      ar: "نحاس ورخام وبساط يبتلع الخطوات. البيوت من هذا النوع لا تعرض القوة. تؤجّلها بجمال حتى الباب.",
      ru: "Латунь, мрамор и ковёр, глотающий шаги. Такие дома не выставляют власть. Они красиво откладывают её — до самой двери.",
    },
  },
  {
    img: "08",
    outlet: "Esquire",
    date: "2025-08-16",
    kind: "campaign",
    title: {
      en: "A supper that never needed a list",
      ar: "عشاء لم يحتج إلى قائمة",
      ru: "Ужин, которому не нужен был список",
    },
    lede: {
      en: "Candlelight, crystal, and three empty seats left on purpose. The evening was complete before anyone sat down.",
      ar: "ضوء شموع وكريستال وثلاثة مقاعد فارغة تُركت عمدًا. اكتملت الأمسية قبل أن يجلس أحد.",
      ru: "Свечи, хрусталь и три пустых места, оставленных нарочно. Вечер был завершён ещё до того, как кто-то сел.",
    },
  },
  {
    img: "09",
    outlet: "Marie Claire",
    date: "2025-07-04",
    kind: "dispatch",
    title: {
      en: "Dawn papers, still warm",
      ar: "صحف الفجر، ما زالت دافئة",
      ru: "Утренние газеты, ещё тёплые",
    },
    lede: {
      en: "The first edition arrives before the city admits it is morning. Whoever placed the story had already left the building.",
      ar: "تصل الطبعة الأولى قبل أن تعترف المدينة بالصباح. من وضع الخبر كان قد غادر المبنى.",
      ru: "Первый выпуск приходит раньше, чем город признаёт утро. Тот, кто поставил материал, уже покинул здание.",
    },
  },
  {
    img: "10",
    outlet: "Associated Press",
    date: "2025-06-21",
    kind: "event",
    title: {
      en: "Velvet, gold rope, no logo",
      ar: "مخمل وحبل ذهب ولا شعار",
      ru: "Бархат, золотой шнур, без логотипа",
    },
    lede: {
      en: "A curtain photographed as if it were a face. The house understands that luxury, at its highest, is withholding.",
      ar: "ستار صُوِّر كأنه وجه. تفهم الدار أن الفخامة في ذروتها هي الإمساك.",
      ru: "Занавес, снятый так, будто это лицо. Дом понимает: высшая роскошь — в умении не показывать.",
    },
  },
  {
    img: "11",
    outlet: "Forbes",
    date: "2025-05-30",
    kind: "cover",
    title: {
      en: "The gown that closed the season",
      ar: "الفستان الذي أغلق الموسم",
      ru: "Платье, которым закрыли сезон",
    },
    lede: {
      en: "One silhouette, held in a pool of light. By morning the photograph had already become the memory of the night.",
      ar: "ظل واحد، ممسوك في بركة ضوء. وفي الصباح كان للصورة أن تكون ذكرى الليل.",
      ru: "Один силуэт в луже света. К утру снимок уже стал памятью о ночи.",
    },
  },
  {
    img: "12",
    outlet: "Tatler",
    date: "2025-04-18",
    kind: "interview",
    title: {
      en: "What he does not say on camera",
      ar: "ما لا يقوله أمام الكاميرا",
      ru: "То, чего он не говорит в кадр",
    },
    lede: {
      en: "The useful answers live in the pause. A long conversation, edited down to the sentences that can survive reprint.",
      ar: "الإجابات النافعة تسكن في الوقفة. حديث طويل اختُصر إلى الجمل التي تصمد أمام إعادة الطبع.",
      ru: "Нужные ответы живут в паузе. Длинный разговор, сжатый до фраз, которые выдержат перепечатку.",
    },
  },
  {
    img: "13",
    outlet: "Esquire",
    date: "2025-03-09",
    kind: "event",
    title: {
      en: "Front row, second language",
      ar: "الصف الأول، اللغة الثانية",
      ru: "Первый ряд, второй язык",
    },
    lede: {
      en: "The collection was shown once. The room understood it twice — in English, then in the language the hosts actually speak.",
      ar: "عُرضت المجموعة مرة. وفهمتها الغرفة مرتين — بالإنجليزية، ثم باللغة التي يتكلمها المضيفون فعلًا.",
      ru: "Коллекцию показали один раз. Зал понял её дважды — по-английски, затем на языке, на котором хозяева говорят на самом деле.",
    },
  },
  {
    img: "14",
    outlet: "Marie Claire",
    date: "2025-02-14",
    kind: "profile",
    title: {
      en: "The collection no one catalogues",
      ar: "المجموعة التي لا يفهرسها أحد",
      ru: "Коллекция, которую никто не каталогизирует",
    },
    lede: {
      en: "Bound volumes, no bookplate. The owner reads them; the public is permitted only the cover.",
      ar: "مجلدات مجلدة بلا ختم ملكية. يقرأها صاحبها؛ ويُسمح للجمهور بالغلاف فقط.",
      ru: "Переплёты без экслибриса. Их читает хозяин; публике дозволена только обложка.",
    },
  },
  {
    img: "15",
    outlet: "Associated Press",
    date: "2025-01-07",
    kind: "dispatch",
    title: {
      en: "Markets open; the story is already written",
      ar: "تُفتح الأسواق؛ والقصة مكتوبة سلفًا",
      ru: "Рынки открылись — история уже написана",
    },
    lede: {
      en: "A morning note that arrived before the bell. The numbers would follow. The sentence had already chosen its tense.",
      ar: "ملاحظة صباحية وصلت قبل الجرس. الأرقام ستأتي لاحقًا. والجملة كانت قد اختارت زمنها.",
      ru: "Утренняя записка пришла раньше колокола. Цифры подтянутся. Предложение уже выбрало своё время.",
    },
  },
  {
    img: "16",
    outlet: "Forbes",
    date: "2024-12-12",
    kind: "campaign",
    title: {
      en: "Silk, shadow, a single sentence",
      ar: "حرير وظل وجملة واحدة",
      ru: "Шёлк, тень, одна фраза",
    },
    lede: {
      en: "The December cover refused a headline. It offered fabric, darkness, and one line the reader could not skim.",
      ar: "رفض غلاف ديسمبر عنوانًا. قدّم قماشًا وظلامًا وسطرًا لا يمكن للقارئ أن يمرّ عليه مرور الكرام.",
      ru: "Декабрьская обложка отказалась от заголовка. Она дала ткань, темноту и одну строку, которую нельзя пробежать глазами.",
    },
  },
  {
    img: "17",
    outlet: "Tatler",
    date: "2024-11-22",
    kind: "society",
    title: {
      en: "The guest who was never announced",
      ar: "الضيف الذي لم يُعلن عنه",
      ru: "Гость, которого так и не объявили",
    },
    lede: {
      en: "No card, no toast, no photograph at the door. Those who needed to know had already taken their seats.",
      ar: "لا بطاقة ولا نخب ولا صورة عند الباب. من كان يحتاج أن يعرف كان قد جلس.",
      ru: "Ни карточки, ни тоста, ни снимка у двери. Те, кому следовало знать, уже заняли места.",
    },
  },
  {
    img: "18",
    outlet: "Esquire",
    date: "2024-10-05",
    kind: "launch",
    title: {
      en: "She edits the night before it happens",
      ar: "تحرّر الليل قبل أن يحدث",
      ru: "Она монтирует ночь до того, как она случится",
    },
    lede: {
      en: "A conversation about sequence: who enters, who is lit, who is left unnamed. Fashion, here, is a form of protocol.",
      ar: "حديث عن التسلسل: من يدخل، من يُضاء، من يُترك بلا اسم. الأزياء هنا شكل من البروتوكول.",
      ru: "Разговор о последовательности: кто входит, кого освещают, кого оставляют без имени. Мода здесь — форма протокола.",
    },
  },
  {
    img: "19",
    outlet: "Marie Claire",
    date: "2024-09-16",
    kind: "city",
    title: {
      en: "Towers that keep their own counsel",
      ar: "أبراج تحتفظ بمشورتها",
      ru: "Башни, которые держат совет сами",
    },
    lede: {
      en: "A night study of a skyline that does not perform. Capital, in this telling, is a light left on in a private floor.",
      ar: "دراسة ليلية لأفق لا يؤدّي عرضًا. رأس المال، في هذا السرد، ضوء متروك في طابق خاص.",
      ru: "Ночной этюд силуэта, который не выступает. Капитал в этом рассказе — свет, оставленный на частном этаже.",
    },
  },
  {
    img: "20",
    outlet: "Associated Press",
    date: "2024-08-28",
    kind: "event",
    title: {
      en: "Spotlight, then silence",
      ar: "ضوء ثم صمت",
      ru: "Прожектор, затем тишина",
    },
    lede: {
      en: "He spoke for eleven minutes. The room did not applaud. It adjusted, which is rarer, and more useful.",
      ar: "تكلم إحدى عشرة دقيقة. لم تصفّق الغرفة. بل عدّلت وضعها، وهذا أندر وأنفع.",
      ru: "Он говорил одиннадцать минут. Зал не аплодировал. Он перестроился — это реже и нужнее.",
    },
  },
  {
    img: "21",
    outlet: "Financial Times",
    date: "2024-07-19",
    kind: "letter",
    title: {
      en: "A pen, a blotter, a country",
      ar: "قلم ونشاف وبلد",
      ru: "Перо, промокашка, страна",
    },
    lede: {
      en: "Handwritten notes still move ministries. The photograph is of the instrument; the news is of the recipient.",
      ar: "الملاحظات بخط اليد ما زالت تحرّك الوزارات. الصورة للأداة؛ والخبر لمن استلمها.",
      ru: "Рукописные записки всё ещё двигают министерства. На снимке — инструмент; новость — в адресате.",
    },
  },
  {
    img: "22",
    outlet: "Vogue",
    date: "2024-06-11",
    kind: "profile",
    title: {
      en: "The chair at the end of the table",
      ar: "الكرسي في نهاية المائدة",
      ru: "Кресло в конце стола",
    },
    lede: {
      en: "Not the loudest seat. The one from which the evening is decided. A study in how power prefers upholstery to podium.",
      ar: "ليس المقعد الأعلى صوتًا. المقعد الذي يُحسم منه المساء. دراسة في كيف تفضّل القوة التنجيد على المنصة.",
      ru: "Не самое громкое место. То, с которого решают вечер. Этюд о том, как власть предпочитает обивку кафедре.",
    },
  },
  {
    img: "23",
    outlet: "Wall Street Journal",
    date: "2024-05-03",
    kind: "cover",
    title: {
      en: "Navy, and nothing else",
      ar: "كحلي، ولا شيء غيره",
      ru: "Синий — и больше ничего",
    },
    lede: {
      en: "A cover that declined jewellery, location, even a name. Colour as rank. Cloth as biography.",
      ar: "غلاف رفض الحلي والمكان حتى الاسم. اللون رتبة. والقماش سيرة.",
      ru: "Обложка без украшений, без места, даже без имени. Цвет как ранг. Ткань как биография.",
    },
  },
  {
    img: "24",
    outlet: "Bloomberg",
    date: "2024-04-21",
    kind: "dispatch",
    title: {
      en: "The briefing that never leaked",
      ar: "الإحاطة التي لم تتسرّب",
      ru: "Брифинг, который не утёк",
    },
    lede: {
      en: "Paper, coffee, dawn. The copy was filed at 5:40. By the time the city woke, the story had already taken its final shape.",
      ar: "ورق وقهوة وفجر. أُرسل النص في الخامسة وأربعين. وحين استيقظت المدينة كانت القصة قد اتخذت شكلها الأخير.",
      ru: "Бумага, кофе, рассвет. Текст сдали в 5:40. К тому моменту, как город проснулся, история уже приняла окончательную форму.",
    },
  },
  {
    img: "25",
    outlet: "Vanity Fair",
    date: "2024-03-14",
    kind: "society",
    title: {
      en: "Three empty seats, on purpose",
      ar: "ثلاثة مقاعد فارغة، عمدًا",
      ru: "Три пустых места — нарочно",
    },
    lede: {
      en: "Absence, correctly staged, is a guest. The table understood. So did everyone who was not invited to sit.",
      ar: "الغياب، إذا أُخرج بإتقان، ضيف. فهمت المائدة. وفهم من لم يُدعَ للجلوس.",
      ru: "Отсутствие, верно поставленное, — тоже гость. Стол это понял. И те, кого не посадили, — тоже.",
    },
  },
  {
    img: "26",
    outlet: "GQ",
    date: "2024-02-08",
    kind: "interview",
    title: {
      en: "Rooms that remember their owners",
      ar: "غرف تتذكر أصحابها",
      ru: "Комнаты, которые помнят хозяев",
    },
    lede: {
      en: "An interview conducted standing, in a corridor that does not hurry. The architecture, she said, is the first publicist.",
      ar: "حوار أُجري وقوفًا، في ممر لا يستعجل. قالت: العمارة هي أول مستشار إعلامي.",
      ru: "Интервью стоя, в коридоре, который никуда не торопится. Архитектура, сказала она, — первый пиарщик.",
    },
  },
  {
    img: "27",
    outlet: "Architectural Digest",
    date: "2024-01-26",
    kind: "launch",
    title: {
      en: "The last dance before the cameras left",
      ar: "الرقصة الأخيرة قبل أن تغادر الكاميرات",
      ru: "Последний танец до того, как камеры ушли",
    },
    lede: {
      en: "When the lights cooled, the evening became private again. That is the hour the house prefers — and the one it is retained to protect.",
      ar: "حين بردت الأضواء عاد المساء خاصًا. تلك الساعة تفضّلها الدار — وهي التي تُعهَد إليها بحمايتها.",
      ru: "Когда огни остыли, вечер снова стал частным. Этот час дом любит больше всего — и его его нанимают беречь.",
    },
  },
  {
    img: "28",
    outlet: "Monocle",
    date: "2023-12-09",
    kind: "campaign",
    title: {
      en: "Measured, never modest",
      ar: "موزون، وليس متواضعًا",
      ru: "Сдержан, но не скромен",
    },
    lede: {
      en: "A winter portrait in navy upholstery. He does not perform humility. He performs proportion, which lasts longer.",
      ar: "بورتريه شتوي على تنجيد كحلي. لا يؤدّي التواضع. يؤدّي التناسب، وهو أطول عمرًا.",
      ru: "Зимний портрет на синей обивке. Он не играет в скромность. Он держит пропорцию — она живёт дольше.",
    },
  },
  {
    img: "29",
    outlet: "Reuters",
    date: "2023-11-17",
    kind: "city",
    title: {
      en: "The hour the newsroom still smells of ink",
      ar: "الساعة التي لا تزال غرفة الأخبار تشم فيها الحبر",
      ru: "Час, когда в редакции ещё пахнет краской",
    },
    lede: {
      en: "Before the first coffee, the first edition. A city brief written for people who still pick up paper with both hands.",
      ar: "قبل أول قهوة، الطبعة الأولى. موجز مدينة كُتب لمن ما زال يمسك الورق بكلتا يديه.",
      ru: "До первого кофе — первый выпуск. Городская сводка для тех, кто всё ещё берёт бумагу двумя руками.",
    },
  },
  {
    img: "30",
    outlet: "Harper’s Bazaar",
    date: "2023-10-02",
    kind: "letter",
    title: {
      en: "The season, bound in cloth",
      ar: "الموسم، مجلّد بالقماش",
      ru: "Сезон, переплетённый тканью",
    },
    lede: {
      en: "Thirty stories later, the book closes as it opened: quietly, on velvet, with nothing left to prove in the headline.",
      ar: "بعد ثلاثين قصة يُغلق الدفتر كما فُتح: بهدوء، على مخمل، بلا شيء يُثبت في العنوان.",
      ru: "Тридцать историй спустя книга закрывается так же, как открылась: тихо, на бархате, без нужды что-то доказывать заголовком.",
    },
  },
];
